//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by f:\Project\VCproject\Orwell\VVMapEditor\Res\En\VVMapEditor.rc
//
#define IDD_ABOUTBOX                    100
#define ID_COMPILE_PROGRESS             103
#define ID_MAP_COORD                    110
#define ID_ABSOLUTE_COORD               111
#define IDR_MAINFRAME                   128
#define IDR_VVMAPETYPE                  129
#define IDD_CREATE_AREA                 130
#define IDD_ID                          131
#define IDD_MERGE                       132
#define IDD_SHORT                       133
#define IDC_CROSS2                      134
#define IDR_MASTER                      135
#define IDR_POINTS                      137
#define IDD_LOADID                      138
#define IDD_SETID                       139
#define IDR_MENU                        140
#define IDD_VIDEOCOMPRESSION            141
#define IDR_TOOLBAR1                    142
#define IDD_ANCHOR                      144
#define IDB_BITMAP1                     145
#define IDB_CONTROL_POINT               145
#define IDB_PAUSE                       146
#define IDD_MAP_SCALE                   148
#define IDB_CONTROL_ANCHOR              149
#define IDD_OPTIONS                     150
#define IDD_COLOR_OPTIONS               151
#define IDB_ANCHOR_ON_MAP               152
#define IDB_GETXY                       153
#define IDC_EDIT1                       1000
#define IDC_LIST1                       1000
#define IDC_LIST_ANCHORS                1000
#define IDC_LIST_OBJECT                 1000
#define IDC_ID_ALL                      1001
#define IDC_ID_SELECT                   1002
#define IDC_ADD                         1003
#define IDC_ADD_ALL                     1004
#define IDC_REMOVE                      1005
#define IDC_REMOVE_ALL                  1006
#define IDC_VER_EDITOR                  1007
#define IDC_VER_INT                     1008
#define IDC_COMBO1                      1008
#define IDC_COMBO_ANCHORS               1008
#define IDC_VER_SRS                     1009
#define IDC_BUTTON_ADD                  1009
#define IDC_SHORT                       1010
#define IDC_STATIC_X                    1010
#define IDC_LEFT                        1011
#define IDC_STATIC_Y                    1011
#define IDC_RIGHT                       1012
#define IDC_STATIC_Z                    1012
#define IDC_LIST2                       1014
#define IDC_EDIT_X                      1015
#define IDC_EDIT_Y                      1016
#define IDC_EDIT_Z                      1018
#define IDC_LIST_DISTANCE               1026
#define IDC_SPIN_MRU                    1027
#define IDC_FILTER_NONE                 1029
#define IDC_FILTER_WEAK                 1030
#define IDC_FILTER_STRONG               1031
#define IDC_EDIT_MRU                    1032
#define IDC_LIST_MASTER                 1034
#define IDC_LIST_POINT                  1035
#define IDC_EDIT_THICKNESS              1036
#define IDC_SPIN_EXTENT                 1037
#define IDC_SPIN_THICKNESS              1038
#define IDC_EDIT_EXTENT                 1039
#define IDC_STATIC_CROSS                1040
#define IDC_STATIC_ANCHOR_COLOR         1042
#define IDC_STATIC_REF_COLOR            1043
#define IDC_STATIC_MAPANCHOR_COLOR      1044
#define IDC_STATIC_EXTENT_COLOR         1045
#define IDC_STATIC_COLOR_POINTNUMBER    1046
#define IDC_ANCHOR_GRID                 1049
#define IDC_COMP_LIST                   1267
#define IDC_USE_DATARATE                1268
#define IDC_DATARATE                    1269
#define IDC_STATIC_DATARATE             1270
#define IDC_USE_KEYFRAMES               1271
#define IDC_KEYRATE                     1272
#define IDC_STATIC_KEYFRAMES            1273
#define IDC_SIZE_RESTRICTIONS           1275
#define IDC_CONFIGURE                   1276
#define IDC_ABOUT                       1277
#define IDC_STATIC_DELTA                1278
#define IDC_STATIC_FOURCC               1279
#define IDC_STATIC_DRIVER               1280
#define IDC_STATIC_QUALITY_LABEL        1281
#define IDC_QUALITY_SLIDER              1282
#define IDC_EDIT_QUALITY                1283
#define IDS_EXC_INVALID_IMAGE_FILE      15446
#define IDS_FILTER_IMAGE                15447
#define IDS_FILTER_VIDEO                15448
#define IDS_ERR_WRONGID                 15449
#define IDS_FILTER_POLYGON              15450
#define IDS_REG_DB                      15451
#define IDS_REG_DB_PARAM                15452
#define IDS_EXC_VIDEO_SERVER            15453
#define IDS_EXC_VIDEO_IMAGE             15454
#define ID_CB_ALLOW_DOCKING             15455
#define ID_CB_CLOSE                     15456
#define IDS_MENU_NEW                    15457
#define IDS_FILTER_NONE                 15458
#define IDS_FILTER_WEAK                 15459
#define IDS_FILTER_STRONG               15460
#define IDS_NO_IMAGE                    15461
#define IDS_ANCHOR_NUMBER               15462
#define IDS_ANCHOR_X                    15463
#define IDS_ANCHOR_Y                    15464
#define IDS_ANCHOR_Z                    15465
#define IDS_ANCHOR_RELATIVE             15466
#define IDS_ANCHOR_STATIC_X             15467
#define IDS_ANCHOR_STATIC_Y             15468
#define IDS_ANCHOR_STATIC_Z             15469
#define IDS_ANCHOR_STATIC_RO            15470
#define IDS_ANCHOR_STATIC_PSI           15471
#define IDS_ANCHOR_STATIC_PHI           15472
#define IDS_ADD_ITEMS                   15473
#define IDS_MAP                         15474
#define IDS_FMT_EXTENT                  15475
#define IDS_NEW_DISTANCE                15476
#define IDS_NEW_REFERENCE_POINT         15477
#define IDS_FMT_GROUP                   15478
#define IDS_REFERENCE_POINT             15479
#define IDS_SUPPORT_POINTS              15480
#define IDS_REFERENCE_POINTS            15481
#define IDS_COLUMN_POINTS               15482
#define IDS_COLUMN_DISTANCES            15483
#define IDS_FMT_ID                      15484
#define IDS_PAUSE                       15485
#define IDS_VMT_FILTER                  15486
#define IDS_NO                          15487
#define IDS_YES                         15488
#define IDS_FMT_MERGE_AREA_SIZE         15489
#define IDS_FMT_MERGE                   15490
#define IDS_COLUMN_FROM                 15491
#define IDS_COLUMN_TO                   15492
#define IDS_COLUMN_QUALITY              15493
#define IDS_INVALID_DATA_SOURCE         15494
#define IDS_DB_NOT_CONNECTED            15495
#define IDS_TABLE_NOT_CONNECTED         15496
#define IDS_POINTS                      15497
#define IDS_EXTENTS                     15498
#define IDS_DIFF_IDS                    15499
#define IDS_CUSTOM_OPTIONS              15500
#define IDS_OPTIONS                     15501
#define IDS_TT_CROSS_EXTENT             15502
#define IDS_TT_CROSS_THICKNESS          15503
#define IDS_MASTER                      15504
#define IDS_COLOR                       15505
#define IDS_GROUP                       15506
#define IDS_DB_CONNECTION               15507
#define IDS_NO_DATA                     15508
#define IDS_DB_SAVE                     15509
#define ID_EDIT_MAP                     32771
#define ID_EDIT_POINTS                  32772
#define ID_EDIT_EXTENTS                 32773
#define ID_VIEW_POINTS                  32774
#define ID_VIEW_EXTENTS                 32775
#define ID_VIEW_EXTENT_TABLES           32776
#define ID_VIEW_POLYGONS                32777
#define ID_VIEW_GETXY_POINTS            32778
#define ID_COR_CREATE                   32779
#define ID_MASTER_IMAGE                 32800
#define ID_MASTER_VIDEO                 32801
#define ID_MASTER_CAMERA                32802
#define ID_MASTER_EMTPY                 32803
#define ID_MASTER_ALLBG                 32804
#define ID_MASTER_SETID                 32805
#define ID_MASTER_SRS                   32806
#define ID_MASTER_SAVE_TABLE            32807
#define ID_MASTER_OPEN_TABLE            32808
#define ID_MAP_IMAGE                    32809
#define ID_MAP_EXPORT                   32810
#define ID_GROUP_DELETE                 32811
#define ID_POINTS_DELETE                32812
#define ID_VIEW_ADDWINDOW               32813
#define ID_VIDEO_PLAY                   32815
#define ID_VIDEO_STOP                   32816
#define ID_VIDEO_PAUSE                  32817
#define ID_VIDEO_RECORD                 32818
#define ID_VIDEO_PROPERTY               32819
#define ID_WINDOW_QUALITY               32820
#define ID_VIEW_HEIGHTS                 32821
#define ID_EDIT_MAP_ORIGIN              32822
#define ID_EDIT_IZ                      32823
#define ID_VIEW_IZ                      32824
#define ID_EDIT_SP                      32825
#define ID_EDIT_RP                      32826
#define ID_EDIT_OPTIONS                 32827
#define ID_VIEW_POINT_NUMBER            32828
#define ID_EDIT_INTERFACE_OPTIONS       32829
#define ID_WINDOW_CLOSE_ALL             32830
#define ID_COR_MAP_PANORAMA             32831
#define ID_FILE_SAVE_DB                 32832
#define ID_FILE_OPEN_DB                 32834
#define ID_COR_COMPILE                  32880
#define ID_COR_MERGE_2MASTERS           32881
#define ID_COR_STOP                     32883
#define ID_WINDOWS_CAMERA               32884
#define ID_WINDOW_MERGE                 32885
#define ID_WINDOW_POINTS                32886
#define ID_SCALECOMBO                   32899
#define ID_MERGE                        33000
#define ID_MASTER_WINDOW                33100
#define ID_MERGE_DELETE                 33300
#define ID_MENU_GROUP                   33400
#define ID_EXTENT_MAP                   33500
#define ID_MENU_ANCHOR                  33500
#define ID_IZ_EDIT                      33600
#define ID_IZ_VIEW                      33700

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32837
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
